### ISSUE TITLE
Unable to run WeMix-LLaMA2-13B-MM

### ISSUE THREAD

**Issue by Perseus14** [Alpha-VLLM/WeMix-LLM#1]
I have followed the procedure and installed all the necessary packages and downloaded the model but when I run it. It gives me an error.

Infra:
- 2 T4 GPU
- 16 CPU - 120 GB 

Command: 
```
$wemix_weight=wemix_models/WeMix-LLaMA2-13B-MM/
$CUDA_VISIBLE_DEVICES=0,1 torchrun --nproc-per-node=2 demos/single_turn_mm.py --llama_config ${wemix_weight}/params.json -tokenizer_path ${wemix_weight}/tokenizer.model --pretrained_path ${wemix_weight} --quant
```
Error:
```
WARNING! Found unequal replicas of non-tensor-parallel params: name=llma.start_img, ranks=[0, 1], max_diff=0.0078125.
[06:52:51.122277] WARNING! Found unequal replicas of non-tensor-parallel params: name=llma.end_img, ranks=[0, 1], max_diff=0.0078125.[06:52:51.122289] 
WARNING! Found unequal replicas of non-tensor-parallel params: name=llma.end_img, ranks=[0, 1], max_diff=0.0078125.
[06:52:51.813480] [06:52:51.813473] WARNING! Found unequal replicas of non-tensor-parallel params: name=llma.layers.0.attention_norm.weight, ranks=[0, 1], max_diff=0.0009765625.WARNING! Found unequal replicas of non-tensor-parallel params: name=llma.layers.0.attention_norm.weight, ranks=[0, 1], max_diff=0.0009765625.

[06:52:51.815362] [06:52:51.815367] WARNING! Found unequal replicas of non-tensor-parallel params: name=llma.layers.0.ffn_norm.weight, ranks=[0, 1], max_diff=0.0009765625.WARNING! Found unequal replicas of non-tensor-parallel params: name=llma.layers.0.ffn_norm.weight, ranks=[0, 1], max_diff=0.0009765625.

[06:52:52.643916] WARNING! Found unequal replicas of non-tensor-parallel params: name=llma.layers.1.attention_norm.weight, ranks=[0, 1], max_diff=0.001953125.
[06:52:52.644676] WARNING! Found unequal replicas of non-tensor-parallel params: name=llma.layers.1.ffn_norm.weight, ranks=[0, 1], max_diff=0.0009765625.
[06:52:53.249451] WARNING! Found unequal replicas of non-tensor-parallel params: name=llma.layers.2.attention_norm.weight, ranks=[0, 1], max_diff=0.001953125.
[06:52:53.249632] WARNING! Found unequal replicas of non-tensor-parallel params: name=llma.layers.2.ffn_norm.weight, ranks=[0, 1], max_diff=0.001953125.
[06:52:53.732775] WARNING! Found unequal replicas of non-tensor-parallel params: name=llma.layers.3.attention_norm.weight, ranks=[0, 1], max_diff=0.001953125.
[06:52:53.732951] WARNING! Found unequal replicas of non-tensor-parallel params: name=llma.layers.3.ffn_norm.weight, ranks=[0, 1], max_diff=0.001953125.
[06:52:54.338825] WARNING! Found unequal replicas of non-tensor-parallel params: name=llma.layers.4.attention_norm.weight, ranks=[0, 1], max_diff=0.00390625.
[06:52:54.339070] WARNING! Found unequal replicas of non-tensor-parallel params: name=llma.layers.4.ffn_norm.weight, ranks=[0, 1], max_diff=0.001953125.
[06:52:55.104080] WARNING! Found unequal replicas of non-tensor-parallel params: name=llma.layers.5.attention_norm.weight, ranks=[0, 1], max_diff=0.00390625.
[06:52:55.104356] WARNING! Found unequal replicas of non-tensor-parallel params: name=llma.layers.5.ffn_norm.weight, ranks=[0, 1], max_diff=0.001953125.
[06:52:55.610567] WARNING! Found unequal replicas of non-tensor-parallel params: name=llma.layers.6.attention_norm.weight, ranks=[0, 1], max_diff=0.00390625.
[06:52:55.610782] WARNING! Found unequal replicas of non-tensor-parallel params: name=llma.layers.6.ffn_norm.weight, ranks=[0, 1], max_diff=0.001953125.
[06:52:56.265406] WARNING! Found unequal replicas of non-tensor-parallel params: name=llma.layers.7.attention_norm.weight, ranks=[0, 1], max_diff=0.00390625.
[06:52:56.265595] WARNING! Found unequal replicas of non-tensor-parallel params: name=llma.layers.7.ffn_norm.weight, ranks=[0, 1], max_diff=0.001953125.
[06:52:56.918251] WARNING! Found unequal replicas of non-tensor-parallel params: name=llma.layers.8.attention_norm.weight, ranks=[0, 1], max_diff=0.00390625.
[06:52:56.918580] WARNING! Found unequal replicas of non-tensor-parallel params: name=llma.layers.8.ffn_norm.weight, ranks=[0, 1], max_diff=0.001953125.
[06:52:57.790585] WARNING! Found unequal replicas of non-tensor-parallel params: name=llma.layers.9.attention_norm.weight, ranks=[0, 1], max_diff=0.00390625.
[06:52:57.790749] WARNING! Found unequal replicas of non-tensor-parallel params: name=llma.layers.9.ffn_norm.weight, ranks=[0, 1], max_diff=0.001953125.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 15642 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 1 (pid: 15643) of binary: /home/rishabh_manoj_valuelabs_com/anaconda3/envs/accessory/bin/python
Traceback (most recent call last):
  File "/home/rishabh_manoj_valuelabs_com/anaconda3/envs/accessory/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/rishabh_manoj_valuelabs_com/anaconda3/envs/accessory/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/rishabh_manoj_valuelabs_com/anaconda3/envs/accessory/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/rishabh_manoj_valuelabs_com/anaconda3/envs/accessory/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/rishabh_manoj_valuelabs_com/anaconda3/envs/accessory/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/rishabh_manoj_valuelabs_com/anaconda3/envs/accessory/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
demos/single_turn_mm.py FAILED
------------------------------------------------------------
```

**Comment by linziyi96** [comment]
Hi, thanks for your interest!

You are seeing the warning because of a minor problem with our released checkpoints but it should not lead to a crash. To explain in a little more detail, it is a problem in our tensor-parallel gradient clipping implementation which may calculate the clipping factors differently across ranks and consequently scales the replicated parameters to different values. It should be fixed by now and we will update the checkpoints soon.

You may try to use only 1 GPU in your command (i.e., changing ``CUDA_VISIBLE_DEVICES`` to a single device id and use ``--nproc_per_node=1`` in ``torchrun``), as you are using quantization and our implementation currently does not support using quantized models with more than 1 GPU. If that still does not solve your problem, we may need to look at a few lines before the warning messages for the exact error message.

**Comment by Perseus14** [comment]
What's the recommended infra if I want to run 13B without quant? 40GB GPU?

**Comment by linziyi96** [comment]
Without quant the memory requirement should be around 28GB so 40GB should be fine. I believe 32GB is also ok but haven’t tried it yet.

**Comment by linziyi96** [comment]
Without quant we also support using 2 GPUs so your 2*T4-16GB may also be used. Just need to remove ``--quant`` from and add ``--model_parallel_size 2`` to the originally posted command.

**Comment by Perseus14** [comment]
Hmm, I get this 'FlashAttention only works in Ampere GPU' error while inference on T4 gpus. I tried with A100 40GB GPU and it's working!
